export const CrimeTypes = [
  { ENCrimeType: "Homicide", BNCrimeType: "হত্যা" },
  { ENCrimeType: "Murder", BNCrimeType: "খুন" },
  { ENCrimeType: "Manslaughter", BNCrimeType: "অনিচ্ছাকৃত হত্যাকাণ্ড" },
  { ENCrimeType: "Assault", BNCrimeType: "আক্রমণ" },
  { ENCrimeType: "Aggravated Assault", BNCrimeType: "গুরুতর হামলা" },
  { ENCrimeType: "Simple Assault", BNCrimeType: "সরল আক্রমণ" },
  { ENCrimeType: "Kidnapping", BNCrimeType: "অপহরণ" },
  { ENCrimeType: "Robbery", BNCrimeType: "ডাকাতি" },
  { ENCrimeType: "Armed Robbery", BNCrimeType: "অস্ত্রধারী ডাকাতি" },
  { ENCrimeType: "Burglary", BNCrimeType: "চুরির উদ্দেশ্যে প্রবেশ" },
  { ENCrimeType: "Home Invasion", BNCrimeType: "গৃহ আক্রমণ" },
  { ENCrimeType: "Theft", BNCrimeType: "চুরি" },
  { ENCrimeType: "Larceny", BNCrimeType: "অবৈধ সম্পত্তি গ্রহণ" },
  { ENCrimeType: "Shoplifting", BNCrimeType: "দোকান থেকে চুরি" },
  { ENCrimeType: "Pickpocketing", BNCrimeType: "পকেটমার" },
  { ENCrimeType: "Auto Theft", BNCrimeType: "গাড়ি চুরি" },
  { ENCrimeType: "Carjacking", BNCrimeType: "গাড়ি ছিনতাই" },
  { ENCrimeType: "Arson", BNCrimeType: "অগ্নিসংযোগ" },
  { ENCrimeType: "Vandalism", BNCrimeType: "ধ্বংসাত্মক কার্যকলাপ" },
  { ENCrimeType: "Cybercrime", BNCrimeType: "সাইবার অপরাধ" },
  { ENCrimeType: "Hacking", BNCrimeType: "হ্যাকিং" },
  { ENCrimeType: "Phishing", BNCrimeType: "ফিশিং" },
  { ENCrimeType: "Online Fraud", BNCrimeType: "অনলাইন প্রতারণা" },
  { ENCrimeType: "Cyberstalking", BNCrimeType: "সাইবার অনুসরণ" },
  { ENCrimeType: "Doxxing", BNCrimeType: "ব্যক্তিগত তথ্য ফাঁস" },
  { ENCrimeType: "Identity Theft", BNCrimeType: "পরিচয় চুরি" },
  { ENCrimeType: "Fraud", BNCrimeType: "প্রতারণা" },
  { ENCrimeType: "Credit Card Fraud", BNCrimeType: "ক্রেডিট কার্ড প্রতারণা" },
  { ENCrimeType: "Insurance Fraud", BNCrimeType: "বীমা প্রতারণা" },
  { ENCrimeType: "Securities Fraud", BNCrimeType: "শেয়ার প্রতারণা" },
  { ENCrimeType: "Embezzlement", BNCrimeType: "অসৎ উদ্দেশ্যে তহবিল ব্যবহার" },
  { ENCrimeType: "Bribery", BNCrimeType: "ঘুষ" },
  { ENCrimeType: "Money Laundering", BNCrimeType: "অবৈধ অর্থ হস্তান্তর" },
  { ENCrimeType: "Counterfeiting", BNCrimeType: "জালিয়াতি" },
  { ENCrimeType: "Tax Evasion", BNCrimeType: "কর ফাঁকি" },
  { ENCrimeType: "Extortion", BNCrimeType: "চাঁদাবাজি" },
  { ENCrimeType: "Blackmail", BNCrimeType: "ব্ল্যাকমেইল" },
  { ENCrimeType: "Drug Possession", BNCrimeType: "মাদকের মালিকানা" },
  { ENCrimeType: "Drug Trafficking", BNCrimeType: "মাদক চোরাচালান" },
  { ENCrimeType: "Drug Manufacturing", BNCrimeType: "মাদক উৎপাদন" },
  { ENCrimeType: "Human Trafficking", BNCrimeType: "মানব পাচার" },
  { ENCrimeType: "Smuggling", BNCrimeType: "চোরাচালান" },
  { ENCrimeType: "Racketeering", BNCrimeType: "অবৈধ ব্যবসা" },
  { ENCrimeType: "Organized Crime", BNCrimeType: "সংগঠিত অপরাধ" },
  { ENCrimeType: "Illegal Gambling", BNCrimeType: "অবৈধ জুয়া" },
  { ENCrimeType: "Prostitution", BNCrimeType: "পতিতাবৃত্তি" },
  { ENCrimeType: "Sex Trafficking", BNCrimeType: "যৌন পাচার" },
  { ENCrimeType: "Sexual Assault", BNCrimeType: "যৌন নিপীড়ন" },
  { ENCrimeType: "Rape", BNCrimeType: "ধর্ষণ" },
  { ENCrimeType: "Child Exploitation", BNCrimeType: "শিশু নির্যাতন" },
  { ENCrimeType: "Child Pornography", BNCrimeType: "শিশু পর্নোগ্রাফি" },
  { ENCrimeType: "Indecent Exposure", BNCrimeType: "অশ্লীল প্রকাশ" },
  { ENCrimeType: "Public Intoxication", BNCrimeType: "পাবলিক মাতলামি" },
  { ENCrimeType: "Disorderly Conduct", BNCrimeType: "অসঙ্গত আচরণ" },
  { ENCrimeType: "Loitering", BNCrimeType: "অবৈধভাবে ঘোরাফেরা" },
  { ENCrimeType: "Trespassing", BNCrimeType: "অনধিকার প্রবেশ" },
  { ENCrimeType: "Resisting Arrest", BNCrimeType: "গ্রেফতারের বিরোধিতা" },
  {
    ENCrimeType: "Obstruction of Justice",
    BNCrimeType: "বিচারের প্রতিবন্ধকতা",
  },
  { ENCrimeType: "Perjury", BNCrimeType: "মিথ্যা সাক্ষ্য" },
  {
    ENCrimeType: "Bribery of Officials",
    BNCrimeType: "সরকারি কর্মকর্তাকে ঘুষ",
  },
  { ENCrimeType: "Treason", BNCrimeType: "রাষ্ট্রদ্রোহিতা" },
  { ENCrimeType: "Espionage", BNCrimeType: "গুপ্তচরবৃত্তি" },
  {
    ENCrimeType: "Illegal Firearms Possession",
    BNCrimeType: "অবৈধ অস্ত্র মালিকানা",
  },
];
