export const emergencyContacts = {
  hospitals: [
    {
      name: "Dhaka Medical College Hospital",
      phone: "02-55165088",
      district: "dhaka",
      division: "dhaka",
      address: "Secretariat Rd, Dhaka 1000",
    },
    {
      name: "Square Hospital",
      phone: "02-8144466",
      district: "dhaka",
      division: "dhaka",
      address: "18/F Bir Uttam Qazi Nuruzzaman Sarak, Dhaka 1205",
    },
    {
      name: "Chittagong Medical College Hospital",
      phone: "031-619400",
      district: "chittagong",
      division: "chittagong",
      address: "Chawkbazar, Chattogram",
    },
    {
      name: "Rajshahi Medical College Hospital",
      phone: "0721-775050",
      district: "rajshahi",
      division: "rajshahi",
      address: "Laxmipur, Rajshahi",
    },
    {
      name: "Khulna Medical College Hospital",
      phone: "041-813344",
      district: "khulna",
      division: "khulna",
      address: "Boyra, Khulna",
    },
  ],
  policeStations: [
    {
      name: "Dhaka Metropolitan Police HQ",
      phone: "999",
      district: "dhaka",
      division: "dhaka",
      address: "36 Phoenix Rd, Dhaka 1000",
    },
    {
      name: "Chittagong Metropolitan Police",
      phone: "031-619100",
      district: "chittagong",
      division: "chittagong",
      address: "Kotwali, Chattogram",
    },
    {
      name: "Rajshahi Metropolitan Police",
      phone: "0721-775050",
      district: "rajshahi",
      division: "rajshahi",
      address: "Boalia, Rajshahi",
    },
    {
      name: "Sylhet Metropolitan Police",
      phone: "0821-713020",
      district: "sylhet",
      division: "sylhet",
      address: "Zindabazar, Sylhet",
    },
  ],
  ambulanceServices: [
    {
      name: "Medinova Ambulance Service",
      phone: "02-8611111",
      district: "dhaka",
      division: "dhaka",
      address: "House-71/A, Road-5/A, Dhanmondi",
    },
    {
      name: "Red Crescent Ambulance",
      phone: "01811458600",
      district: "chittagong",
      division: "chittagong",
      address: "Red Crescent Bhaban, Chittagong",
    },
    {
      name: "Rajshahi Ambulance Service",
      phone: "0721-774400",
      district: "rajshahi",
      division: "rajshahi",
      address: "Shaheb Bazar, Rajshahi",
    },
    {
      name: "Sylhet City Ambulance",
      phone: "0821-717777",
      district: "sylhet",
      division: "sylhet",
      address: "Amberkhana, Sylhet",
    },
  ],
  fireServices: [
    {
      name: "Bangladesh Fire Service & Civil Defence HQ",
      phone: "16163",
      district: "dhaka",
      division: "dhaka",
      address: "68/1 Purana Paltan Line, Dhaka-1000",
    },
    {
      name: "Chittagong Fire Service Station",
      phone: "031-631000",
      district: "chittagong",
      division: "chittagong",
      address: "Agrabad, Chattogram",
    },
    {
      name: "Rajshahi Fire Service",
      phone: "0721-772000",
      district: "rajshahi",
      division: "rajshahi",
      address: "Shaheb Bazar, Rajshahi",
    },
    {
      name: "Khulna Fire Service",
      phone: "041-813555",
      district: "khulna",
      division: "khulna",
      address: "Boyra, Khulna",
    },
  ],
};
